"""initial_schema

Revision ID: 8433a1ce4386
Revises: 
Create Date: 2026-09-02 15:55:33.231627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database.models


# revision identifiers, used by Alembic.
revision: str = '8433a1ce4386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('merchant_id', src.database.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('total_payments', sa.Integer(), nullable=True),
    sa.Column('total_failures', sa.Integer(), nullable=True),
    sa.Column('total_recovered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('customer_id', src.database.models.GUID(), nullable=False),
    sa.Column('merchant_id', src.database.models.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('payment_id', src.database.models.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('decision_context', sa.JSON(), nullable=True),
    sa.Column('proposed_action', sa.String(length=50), nullable=True),
    sa.Column('policy_result', sa.String(length=20), nullable=True),
    sa.Column('executed_action', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_failures',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('payment_id', src.database.models.GUID(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=50), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('recovery_actions',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('payment_id', src.database.models.GUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_status', sa.String(length=50), nullable=False),
    sa.Column('predicted_recovery_prob', sa.Float(), nullable=True),
    sa.Column('expected_recovery_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('policy_decision', sa.String(length=20), nullable=True),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_outcomes',
    sa.Column('id', src.database.models.GUID(), nullable=False),
    sa.Column('recovery_action_id', src.database.models.GUID(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_outcomes')
    op.drop_table('recovery_actions')
    op.drop_table('payment_failures')
    op.drop_table('audit_logs')
    op.drop_table('payments')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
